jobs: 
- job: BuildAndScan
  displayName: Build and Scan
  steps:
  - template: ../steps/checkout-self.yaml
  - template: ../steps/debug-vars.yaml

  - task: Docker@2
    displayName: Build image
    inputs:
      containerRegistry: $(dockerStorageAccount)
      repository: $(imageName)
      command: build
      Dockerfile: $(dockerFilePath)
      buildContext: $(dockerContext)
      tags: $(imageTag)
  - task: Docker@2
    displayName: Push image
    inputs:
      containerRegistry: $(dockerStorageAccount)
      repository: $(imageName)
      command: push
      Dockerfile: $(dockerFilePath)
      buildContext: $(dockerContext)
      tags: $(imageTag)
  - task: Docker@2
    displayName: Remove Docker image on agent
    inputs:
      command: rmi # this command not exactly, but still run with arguments
      arguments: $(dockerImage)
  - task: DeleteFiles@1
    displayName: Delete source on agent
    inputs:
      Contents: '*'      
